name: "Build SR-IOV images from PR"
on: 
  workflow_dispatch:
    inputs:
      prurl:
        description: 'PR URL'     
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GHCR_USERNAME: ${{  github.repository_owner }}

jobs:
  images:
    name: SR-IOV images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: ./sriov-operator-pr-images/build-pr.sh ${{ github.event.inputs.prurl }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

