name: "periodics"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "48 5 * * 6"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GHCR_USERNAME: ${{  github.repository_owner }}

jobs:
  images:
    name: SR-IOV images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: ./sriov-operator-pr-images/main.sh
